using UnityEngine;
public static class Language_Extension_012_2
{
    public static string CALM = "A MOOD THAT DESCRIBED A FORM OF INNER CONTENT AND PEACEFUL BEHAVIOR OR ACTION";
    public static string CHEERFUL = "A MOOD THAT DESCRIBES A HAPPY AND FULL OF CHEER BEHAVIOR OR CIRCUMSTANCE";
    public static string CONTENT = "A MOOD THAT DESCRIBES PEACEFUL AND RELAXED REACTIONS BEHAVIORS OR ACTIONS";
    public static string DEFENSIVE = "A MOOD THAT DESCRIBED AS SHOWING DEFENSIVE OR GUARDED BEHAVIORS OR ACTIONS";
    public static string ENERGETIC = "A MOOD THAT DESCRIBES AS FULL OF ENERGY AND PRODUCING ACTION ON THAT ENERGY OR DESCRIBED AS ENERGETIC TO A VAST AMOUNT AND MAKING ACTIONS FROM THE ENERGY ITSELF";
    public static string EXCITED = "A MOOD THAT FORMS BEHAVIORS OR ACTIONS FROM EXCITEMENT";
    public static string GRATEFUL = "ACTION AND OR DECISIONS MADE FROM THANKFULNESS AND OR PLEASURE FROM SOMETHING HAPPENING";
    public static string JOYFUL = "A MOOD DESCRIBED AS ACTIONS FORMING FROM A ENERGY FULL OF JOY";
    public static string LOUD = "A DESCRIBED MOOD WHEN ACTIONS AND DECISIONS ARE MADE FROM LOUD SOUNDS OR EFFECTS";
    public static string MELLOW = "A DESCRIBED MOOD THAT IS MORE RELAXED AND CONSIDERED CALM AND GENTLE";
    public static string NARRATIVE = "A MOOD DESCRIBED BY SPEAKING WITH A SPECIFIC FORM OF MADE EMPHASIS OR EMOTIONS AND OR MOODS AND OR FEELINGS";
    public static string NEUTRAL = "A MOOD THAT DESCRIBES ACTION THAT IS NOT POSITIVE OR NEGATIVE";
    public static string PEACEFUL = "A MOOD THAT DESCRIBES A CONTENT AND RELAXED ACTION OR BEHAVIOR THAT IS SPECIFIC TO THE FORM OF PEACEFUL BEHAVIOR FROM THAT SPECIFIC PERSON";
    public static string QUIET = "A MOOD THAT FORMS FROM SOFT OR LOW VOLUME ACTIONS AND OR REACTIONS AND OR BEHAVIORS";
    public static string RELAXED = "A MOOD THAT DESCRIBES A ACTIONS MADE WITH A RELEASED AMOUNT OF TENSION AND CALM FEELING OR APPROACH FOR MOODS AND OR BEHAVIORS AND OR ALSO EMOTIONS AND FEELINGS WITH THE MOOD ITSELF";
    public static string TALKATIVE = "A MOOD THAT DESCRIBES ACTIONS MADE FROM VERY ENERGETIC REACTIONS OR BEHAVIORS FROM SPEECH AND OR VOCAL RESPONSES";
}