using UnityEngine;
public static class Language_Extension_010_2
{
    public static string COURAGE = "AN EMOTION THAT DESCRIBES AS HAVING A BRAVE FEELING OR STRONG INTENSE COURAGEOUS REACTION AND OR BEHAVIOR AND OR RESPONSE FROM SUBTLE AND OR A LARGE EMOTIONAL RESPONSE";
    public static string FAITH = "AN EMOTION THAT DESCRIBES A STRONG FEELING OF COMMITMENT AND POWER FORMED FROM ONES OWN BELIEFS AND OR VALUES AND OR VIRTUES THAT STRENGTHEN AND FORM FROM A HIGHER SOURCE AND OR FROM ONESELF";
    public static string GRATITUDE = "AN EMOTION THAT DESCRIBES A FEELING OF GRATITUDE OR THANKFUL AND FULL OF POSITIVE FEELINGS AND MOODS AND BEHAVIORS";
    public static string HAPPINESS = "AN EMOTION THAT DESCRIBES A SENSE OF JOY AND HAPPY FEELING";
    public static string HOPE = "AN EMOTION THAT DESCRIBES A STRONG SENSE OF DESIRE TO SUCCEED THROUGH CIRCUMSTANCES WHERE POSSIBILITY IS LOW OR BELOW AVERAGE TO HAPPEN AND THE EMOTION BECOMES STRONGER WHILE WITHIN THAT CIRCUMSTANCE";
    public static string JOY = "AN EMOTION DESCRIBING A SENSE OF OVERWHELMING SATISFACTION FORMED FROM SATISFIED AND HAPPY FEELINGS";
    public static string LOVE = "AN EMOTION DESCRIBING A FEELING THAT CAN ONLY BE DESCRIBED BY THE ACTIONS AND EFFECTS OF THE WAY THE PERSON EXPRESSES THEIR MOODS AND OR EMOTIONS AND OR FEELINGS AND THE ACTIONS AND BEHAVIORS THAT FORM FROM THEM WITHIN THE DEVELOPMENT OF EMOTIONS MOODS AND BEHAVIORS WHEN THEY CREATE THE FEELINGS TOGETHER";
    public static string SERENE = "AN EMOTION DESCRIBING A CALM TEMPERANT FEELING MOOD EMOTION AND FEELING HAPPENING SIMULTANEOUSLY AT THE SAME TIME";
    public static string SERENITY = "AN EMOTION DESCRIBING A SENSE OF CALM UNDERSTANDING THAT HAPPENS WHEN SERENE EMOTIONS MOODS AND BEHAVIORS COLLECT TOGETHER AND MERGE WITH TEMPERANCE AND CALM SATISFACTION";
    public static string SERIOUS = "AN EMOTION DESCRIBING A FORM OF DISCIPLINE AND FOCUSED MINDSET THAT IS CONSIDERED SPECIFIC TO THE TOPIC AND OR WAY THAT SOMETHING IS DESCRIBED";
    public static string TEMPERANCE = "IS A WARM FEELING FORMED FROM GENTLE AND PEACEFUL CIRCUMSTANCES OR SURROUNDINGS";
}