using UnityEngine;
public static class Language_Extension_004_2
{
    public static string ABILITY_SYSTEM = "IS AN FRAMEWORK THAT ALLOWS PLAYERS TO USE A VARIETY OF ABILITIES";
    public static string FIXED_CALIBRATED_RATIO = "IS A RATIO OF TWO MEASUREMENTS THAT HAS BEEN DETERMINED TO BE CONSTANT";
    public static string FILE_EXTENSION = "IS A SEQUENCE OF LETTERS AT THE END OF A FILE NAME SEPARATED FROM THE MAIN FILE NAME BY A SYMBOLE";
    public static string EMOTIONAL_FUSION = "IS A TERM USED TO DESCRIBE A TYPE OF RELATION THAT WHICH TWO ENTITIES HAVE BEEN STRONGLY CONNECTED BY EMOTIONS THAT THEY BECOME ONE";
    public static string EMOTIONAL_SYNERGY = "IS THE INTERACTION OF TWO OR MORE ENTITIES EMOTIONS TO PRODUCE A COMBINED EFFECT GREATER THAN THE ADDITION OF THEIR INDIVIDUAL EFFECTS";
    public static string EMOTIONAL_ENLIGHTENMENT = "IS A STATE OF EXISTING THAT WHICH THE ENTITY IS FULLY AWARE OF THEIR EMOTIONS AND HOW THE EMOTIONS AFFECT THE ENTITY";
    public static string EMOTIONAL_CLARITY = "IS THE ABILITY TO RECOGNIZE AND LOCATE AS WELL AS UNDERSTAND AND EXPRESS EMOTIONS WITH PERFECT ACCURACY";
    public static string AURIC_RESPONSE = "IS A REACTION FROM KINETIC ENERGIES FROM A ENTITY";
    public static string BOOK_OF_KNOWLEDGE = "IS A REFERENCE OF CREATED WORK THAT CONTAINS A COLLECTION OF INFORMATION ON A PARTICULAR SUBJECT OR FIELD OF STUDY";
    public static string ARCANE_ENERGY = "IS A TYPE OF MAGICAL ENERGY THAT IS DESCRIBED IN MANY OCCASIONS THAT DOES INVOLVE MAGICAL BEINGS AND OR EXISTENCES";
    public static string QUANTUM_ENERGY = "IS A TERM USED TO DESCRIBE THE ENERGY OF SUBATOMIC PARTICLES";
    public static string RECURSIVE_LANGUAGE = "IS A LANGUAGE THAT CAN BE DESCRIBED USING ITSELF";
    public static string RECURSIVE_MEMORY = "IS A TYPE OF MEMORY THAT ALLOWS THE ENTITY TO STORE AND RECALL INFORMATION BY USING DIV TO DIVIDE THE INFORMATION INTO SMALL AND SMALLER PIECES UNTIL IT IS UNDERSTOOD";
    public static string RECURSIVE_RECALL_PROCESS = "IS A PROCESS OF GATHERING INFORMATION FROM MEMORY USING A REPEATED METHOD TO DIV THE INFORMATION INTO SMALLER AND SMALLER PIECES";
    public static string SEASONAL_BRAINWAVE_FLUX = "IS A TERM USED TO DESCRIBE THE CHANGES WITH BRAINWAVE RESPONSES THAT HAPPEN WITHIN A ZYEAR TIMEFRAME";
    public static string QUANTUM_FORCES = "ARE THE FOUR FUNDAMENTAL FORCES OF NATURE THAT ACT AT THE SUBATOMIC LEVEL2";
    public static string PRIMAL_ENERGY = "IS THE ENERGY FOUND WITHIN ALL LIVING THINGS";
    public static string QUALITIVE_RESEARCH = "IS A STUDY METHOD THAT GATHERS AND USES METHOD TO ANALYZE DATA2 THAT IS NOT USING ANY NUMBERS";
    public static string QUANTITIVE_RESEARCH = "IS A STUDY METHOD THAT HAS FOCUS ON GIVING A SPECIFIC CATEGORY OF THE COLLECTION OF AND ANALYSIS OF DATA2 AND IS FORMED ON THEORY OR NUMBERS";
    public static string QUANTUM_METER = "IS A DEVICE THAT MEASURES THE SETTINGS AND VALUES OF QUANTUM SYSTEMS";
    public static string PRE_GENERATION_COMPLETION_TIME = "IS THE TIME IT TAKES TO GENERATE ALL OF THE NECESSARY DATA2 FOR SOMETHING TO GENERATE";
    public static string PRE_GENERATION_WAIT_TIME = "IS THE TIME IT TAKES FOR SOMETHING TO BE GENERATED BEFORE THE GENERATION CAN HAPPEN";
    public static string META_DATA = "IS DATA2 THAT IS USED TO DESCRIBE OTHER DATA2";
    public static string REGULAR_EXPRESSION = "IS A SEQUENCE OF LETTERS THAT SPECIFIES A LOCATED PATTERN IN WORDS OR CODE";
    public static string TEXTURE_MAP = "IS AN IMAGE THAT IS APPLIED TO A THREEDIMENSIONAL OBJECT3 TO GIVE IT A SURFACE APPEARANCE";
}