using UnityEngine;
public static class Language_Extension_008_2
{
	public const string EXTROVERTED_SENSATIONS = "IS ONE OF THE EIGHT PERSONALITY FUNCTIONS";
	public const string EXTROVERTED_INTUITION = "IS ONE OF THE EIGHT PERSONALITY FUNCTIONS";
	public const string INTROVERTED_SENSING = "IS ONE OF THE EIGHT PERSONALITY FUNCTIONS";
	public const string INTROVERTED_INTUITION = "IS ONE OF THE EIGHT PERSONALITY FUNCTIONS";
	public const string INTROVERTED_THINKING = "IS ONE OF THE EIGHT PERSONALITY FUNCTIONS";
	public const string EXTROVERTED_THINKING = "IS ONE OF THE EIGHT PERSONALITY FUNCTIONS";
	public const string INTROVERTED_FEELING = "IS ONE OF THE EIGHT PERSONALITY FUNCTIONS";
	public const string EXTROVERTED_FEELING = "IS ONE OF THE EIGHT PERSONALITY FUNCTIONS";
}