using UnityEngine;
public static class Language_Extension_007_2
{
	public const string WIDE_AREA_NETWORK = "IS A NETWORK THAT CAN EXPAND TO A SPECIFIC RANGE OF AREAS WITHIN A SPECIFIC DISTANCE";
	public const string REMOTE_HOST = "IS A DEVICE CONNECTED TO A WIDE_AREA_NETWORK";
	public const string LOCAL_HOST = "IS A DEVICE THAT IS CONNECTED TO AN LAN";
	public const string PERSONAL_HOST = "IS A SMALL DEVICE THAT CAN BE USED BY AN INDIVIDUAL ENTITY";
	public const string HOSTS = "MORE THAN ONE HOST";
	public const string CLIENT_HOST = "IS A GROUP OF ENTITIES THAT REQUEST RESOURCES FROM OTHER HOSTS WITHIN THE NETWORK";
	public const string HOST = "IS A DEVICE THAT IS CONNECTED TO A NETWORK THAT CAN COMMUNICATE WITH OTHER DEVICES WITHIN THE NETWORK";
	public const string HOSTING_SERVICE = "ALLOWS MORE THAN ONE INDIVIDUAL AND GROUP TO MAKE A WEBSITE ACCESSIBLE TO A SPECIFIC NETWORK OR GROUP OF NETWORKS";
	public const string WEB_HOSTING_SERVICE = "IS A TYPE OF NETWORK HOSTING_SERVICE";
	public const string WEB_HOSTING_SERVICES = "MORE THAN ONE WEB_HOSTING_SERVICE";
	public const string SERVER_HOST = "IS A GROUP OF ENTITIES THAT CAN PROVIDE WEB_HOSTING_SERVICES";
	public const string WEBPAGE = "IS A DOCUMENT THAT IS PART OF A WEBSITE";
	public const string WEBPAGES = "MORE THAN ONE WEBPAGE";
	public const string HOSTED = "IS SOMETHING THAT WAS PREVIOUSLY HOST";
	public const string WEB_SERVER = "IS BOTH A COMPUTER THAT HOSTS A WEBSITE AND IS A SOFTWARE PROGRAM THAT SENDS WEBPAGES TO COMPUTERS";
	public const string WEBSITE = "A COLLECTION OF WEBPAGES THAT ARE LINKED TOGETHER AND HOSTED WITHIN A WEB_SERVER";
	public const string WEBSITES = "MORE THAN ONE WEBSITE";
	public const string WEB_HOST = "IS A GROUP OF ENTITIES THAT PROVIDE STORAGE SPACE AND BANDWIDTH FOR WEBSITES";
	public const string WEB_BROWSER = "IS A SOFTWARE PROGRAM MADE TO ALLOW TO ACCESS AND VISIT VIEWABLE WEBSITES";
	public const string CONTROL_PANEL = "IS A GRAPHICUSERINTERFACE THAT ALLOWS A USER TO MANAGE SETTINGS AND FEATURES OF A COMPUTER OR SOFTWARE PROGRAM";
	public const string REMOTE_COMPUTER = "IS A COMPUTER THAT IS NOT PHYSICALLY LOCATED IN THE SAME LOCATION AS THE USER";
	public const string REMOTE_DESKTOP_CONNECTION = "IS A DEVICE THAT ALLOWS A USER TO CONNECT TO A REMOTE_COMPUTER AND CONTROL IT FROM A DIFFERENT LOCATION FROM WHERE THE REMOTE_COMPUTER IS LOCATED";
	public const string WEB_BASED = "DESCRIBES ANYTHING THAT IS ACCESSED BY A NETWORK WHILE USING A WEB_BROWSER";
	public const string REMOTE_SERVER = "IS A COMPUTER THAT IS LOCATED WITHIN A DIFFERENT PHYSICAL LOCATION THAT IS DIFFERENT FROM THE USER AND CAN BE ACCESSED BY A NETWORK USING A REMOTE_DESKTOP_CONNECTION OR A WEB_BASED CONTROL_PANEL";
	public const string EQUIPMENT = "REFERS TO THE TOOLS AND DEVICES THAT ARE USED WITHIN A SPECIFIC GROUP AND OR FIELD";
	public const string LOCAL_HARDWARE = "IS THE PHYSICAL EQUIPMENT THAT IS CONNECTED TO A LAN AND IS LOCATED WITHIN A SINGLE LOCATION";
	public const string CLOUD_GAMING = "IS A IDEA THAT CAN ALLOW A PLAYER TO ACTIVATE A GAME FROM A REMOTE_SERVER RATHER THAN ACTIVATING IT WITHIN LOCAL_HARDWARE";
}